//* This environment file has being generated by set-apiRoute.sh script at:  Thu Jun 2 21:03:40 CEST 2022
 
var apiRoute:string = 'http://probes-project01.apps.ipq49uiq.eastus.aroapp.io';
      export const environment = {
        production: false,
        backendURL:  apiRoute,
        userListURL: apiRoute + '/api/person/all',
        userAddURL:  apiRoute + '/api/person/add'
      };
